### PR TITLE
Add a simple command-line tool and logging of protocol

### PR DESCRIPTION
**Pull request by rytilahti**
I think it's easier to keep just only fork "up-to-date", so in case you want to pull this to your repo it'd be great. Maybe the cli tool will be useful instead of trying to do it through homeassistant.

### CODE REVIEW

**Comment by rytilahti** [comment]
Btw, there's no way currently the get the window state config? I left it unimplemented for now.

**Comment by jannau** [comment]
I agree that's probably best to handle my repo as upstream. I adopted your review comments and pushed to my master.

Factory reset, firmware update and week program functions are the only BLE commads which are not implemented from the Android client app. I suppose one could try if the thermostat exports further information.

**Comment by jannau** [comment]
Merge and rebased onto master

**Comment by rytilahti** [comment]
Thanks for the quick merge!

**Pull request merged**
